name: Deploy Snowpark Apps

# Controls when the action will run. 
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: pip install -r requirements.txt
      
      - name: Configure snowcli
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
          SNOWSQL_ROLE: ${{ secrets.SNOWSQL_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWSQL_WAREHOUSE }}
          SNOWSQL_DATABASE: ${{ secrets.SNOWSQL_DATABASE }}
          SCHEMA_NAME: ${{ secrets.SCHEMA_NAME }}
          
        run: |
          cd $GITHUB_WORKSPACE
          echo "[connections.dev]" > config
          echo "accountname = $SNOWSQL_ACCOUNT" >> config
          echo "username = $SNOWSQL_USER" >> config
          echo "password = $SNOWSQL_PWD" >> config
          echo "rolename = $SNOWSQL_ROLE" >> config
          echo "warehousename = $SNOWSQL_WAREHOUSE" >> config
          echo "dbname = $SNOWSQL_DATABASE" >> config

      - name: Deploy Snowpark apps
        run: |
          echo ${{ secrets.SNOWSQL_ACCOUNT }}
          echo $SNOWSQL_ACCOUNT
          python runsql.py $SNOWSQL_ACCOUNT $SNOWSQL_USER $SNOWSQL_PWD $SNOWSQL_WAREHOUSE $SNOWSQL_DATABASE $SCHEMA_NAME modules/teardown.sql
          python runsql.py $SNOWSQL_ACCOUNT $SNOWSQL_USER $SNOWSQL_PWD $SNOWSQL_WAREHOUSE $SNOWSQL_DATABASE $SCHEMA_NAME modules/setup_snow.sql
          python deploy.py $GITHUB_WORKSPACE
          python runsql.py $SNOWSQL_ACCOUNT $SNOWSQL_USER $SNOWSQL_PWD $SNOWSQL_WAREHOUSE $SNOWSQL_DATABASE $SCHEMA_NAME modules/load_raw.sql
          python runsql.py $SNOWSQL_ACCOUNT $SNOWSQL_USER $SNOWSQL_PWD $SNOWSQL_WAREHOUSE $SNOWSQL_DATABASE $SCHEMA_NAME modules/data_cleaning.sql
          python runsql.py $SNOWSQL_ACCOUNT $SNOWSQL_USER $SNOWSQL_PWD $SNOWSQL_WAREHOUSE $SNOWSQL_DATABASE $SCHEMA_NAME modules/airport_crowd.sql
          python runsql.py $SNOWSQL_ACCOUNT $SNOWSQL_USER $SNOWSQL_PWD $SNOWSQL_WAREHOUSE $SNOWSQL_DATABASE $SCHEMA_NAME modules/hourly_crowd.sql
          python runsql.py $SNOWSQL_ACCOUNT $SNOWSQL_USER $SNOWSQL_PWD $SNOWSQL_WAREHOUSE $SNOWSQL_DATABASE $SCHEMA_NAME modules/carbon_footprint.sql
          python runsql.py $SNOWSQL_ACCOUNT $SNOWSQL_USER $SNOWSQL_PWD $SNOWSQL_WAREHOUSE $SNOWSQL_DATABASE $SCHEMA_NAME modules/seat_occupancy.sql         
          
        
